#########################################################
#                                                       #
#        WARNING: THIS FILE SHOULD NEVER BE USED        #
#              IN PRODUCTION ENVIRONMENTS!              #
#                                                       #
#########################################################

#########################################################
# Node-specific configuration
#########################################################
beneficiary = "0x0000000000000000000000000000000000000000"
node_name = "devnet-node"
network_name = "devnet"
ipc_tx_batch_size = 500
ipc_max_queued_batches = 6
# must be <= ipc_max_queued_batches
ipc_queued_batches_watermark = 3

statesync_threshold = 600
statesync_max_concurrent_requests = 5

#########################################################
# Network-wide configuration
#########################################################
chain_id = 20143

#########################################################
# Node-specific configuration
#########################################################
[bootstrap]
peers = []
# [[bootstrap.peers]]
# address = "127.0.0.1:8001"
# record_seq_num = 0
# secp256k1_pubkey = "03788c5e94a0f1176c70fd1039e35dd74dd201568e85453eee02e6ddbd2ef64406"
# name_record_sig = "c23485d289232ec46a4cc0b804e10c8f72d4ce5d8ce4005430b686c079b64b89113be1939ea9a5f7160c9f1587acc78dc59df27f80b64ee42ce05860279a727801"

[peer_discovery]
self_address = "0.0.0.0:8000"
self_record_seq_num = 0
self_name_record_sig = "85663053b3d719985357b56270ba320abadd1c51e10ea06430f3990d81393dc7770ff661c331bd631afca705029b0fd77cc0f48d46b37c8d8523c73c6af1242801"
refresh_period = 120
request_timeout = 5
unresponsive_prune_threshold = 5
last_participation_prune_threshold = 5000
min_num_peers = 0
max_num_peers = 200

[fullnode_dedicated]
identities = []
# [[fullnode_dedicated.identities]]
# secp256k1_pubkey = "03788c5e94a0f1176c70fd1039e35dd74dd201568e85453eee02e6ddbd2ef64406"

[blocksync_override]
peers = []
# [[blocksync_override.peers]]
# secp256k1_pubkey = "..."

[statesync]
peers = []
# [[statesync.peers]]
# secp256k1_pubkey = "..."

[fullnode_raptorcast]
enable_publisher = false
enable_client = false
raptor10_fullnode_redundancy_factor = 3.0
max_group_size = 10
round_span = 240
invite_lookahead = 120
max_invite_wait = 10
deadline_round_dist = 10
init_empty_round_span = 23
max_num_group = 3
invite_future_dist_min = 1
invite_future_dist_max = 600
invite_accept_heartbeat_ms = 10000

[fullnode_raptorcast.full_nodes_prioritized]
identities = []

[network]
bind_address_host = "0.0.0.0"
bind_address_port = 8000
max_rtt_ms = 300
max_mbps = 1000